# Generated by Django 4.0.5 on 2022-07-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
